---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-curator-curator
  labels:
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch
    app.kubernetes.io/instance: elasticsearch-curator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: curator
data:
  action_file.yml:   |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Clean up all log files with the prefix kubernetes_ in ES older than 10 days"
        options:
          timeout_override:
          continue_if_exception: True
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 10
          field:
          stats_result:
          epoch:
          exclude: False
        - filtertype: pattern
          kind: prefix
          value: kubernetes_
      2:
        action: delete_indices
        description: "Clean up all log files with the prefix jaeger- in ES older than 10 days"
        options:
          timeout_override:
          continue_if_exception: True
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 10
          field:
          stats_result:
          epoch:
          exclude: False
        - filtertype: pattern
          kind: prefix
          value: jaeger-
  config.yml:   |-
    ---
    client:
      hosts:
        - {{ .Values.es.host }}
      port: {{ .Values.es.port }}
      use_ssl: True
      ssl_no_validate: True
    logging:
      loglevel: INFO
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
