ctions:
  1:
    action: delete_indices
    description: "Clean up kbernetes by deleting old indices"
    options:
      timeout_override:
      continue_if_exception: True
      disable_action: False
      ignore_empty_list: True
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      field:
      stats_result:
      epoch:
      exclude: False
    - filtertype: pattern
      kind: prefix
      value: kubernetes_
  2:
    action: delete_indices
    description: "Clean up Jaeger by deleting old indices"
    options:
      timeout_override:
      continue_if_exception: True
      disable_action: False
      ignore_empty_list: True
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      field:
      stats_result:
      epoch:
      exclude: False
    - filtertype: pattern
      kind: prefix
      value: jaeger-
