client:
  hosts:
    - "search-train-hlcvcu7wubl2yrvupsbuineg7a.us-east-1.es.amazonaws.com"
  port: 443
  username: ""
  password: ""
  use_ssl: True
  ssl_no_validate: True
logging:
  loglevel: INFO
  logfile:
  logformat: json
  blacklist: ['opensearch', 'urllib3']
