client:
  hosts:
    - 'opensearh-endpoits'
  port: 443
  username: username
  password: password
  # url_prefix:
  use_ssl: True
  ssl_no_validate: True
logging:
  loglevel: INFO
  logfile:
  logformat: json
  blacklist: ['opensearch', 'urllib3']
