client:
  hosts:
    - 'ur-opensearch-domain'
  port: 443
  username: username
  password: password
  # url_prefix:
  use_ssl: True
  ssl_no_validate: True
logging:
  loglevel: INFO
  logformat: default
  blacklist: ['opensearch', 'urllib3']
